kind: Service
apiVersion: v1
metadata:
  name: demo-app-service
  namespace: demo-app
spec:
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 3000
  type: NodePort
